apiVersion: v1
kind: Service
metadata:
  name: ace
  labels:
    app: ace
spec:
  selector:
    app: ace
  ports:
    - name: ace-http
      port: 7800
      protocol: TCP
      targetPort: 7800
    - name: ace-https
      port: 7843
      protocol: TCP
      targetPort: 7843
    - name: webui
      port: 8080
      protocol: TCP
      targetPort: 7600
  type: NodePort
